export const DEPARTMENTS = [
  "Accounting",
  "Administration",
  "Audit",
  "Business Development",
  "Communications",
  "Corporate Affairs",
  "Creative",
  "Customer Service",
  "Engineering",
  "Finance",
  "General Services",
  "Health & Safety",
  "Human Resources",
  "Information Technology",
  "Legal",
  "Logistics",
  "Marketing",
  "Operations",
  "Procurement",
  "Production",
  "Quality Assurance",
  "Research & Development",
  "Sales",
  "Security",
  "Supply Chain",
  "Training & Development",
  "Department of Agriculture (DA)",
  "Department of Budget and Management (DBM)",
  "Department of Education (DepEd)",
  "Department of Energy (DOE)",
  "Department of Environment and Natural Resources (DENR)",
  "Department of Finance (DOF)",
  "Department of Foreign Affairs (DFA)",
  "Department of Health (DOH)",
  "Department of Human Settlements and Urban Development (DHSUD)",
  "Department of Information and Communications Technology (DICT)",
  "Department of the Interior and Local Government (DILG)",
  "Department of Justice (DOJ)",
  "Department of Labor and Employment (DOLE)",
  "Department of Migrant Workers (DMW)",
  "Department of National Defense (DND)",
  "Department of Public Works and Highways (DPWH)",
  "Department of Science and Technology (DOST)",
  "Department of Social Welfare and Development (DSWD)",
  "Department of Tourism (DOT)",
  "Department of Trade and Industry (DTI)",
  "Department of Transportation (DOTr)",
  "National Economic and Development Authority (NEDA)",
  "Presidential Communications Office (PCO)",
];

export const POSITIONS = [
  "Accounting Assistant",
  "Accounting Clerk",
  "Accounting Manager",
  "Administrative Aide",
  "Administrative Assistant",
  "Administrative Officer",
  "Administrative Supervisor",
  "Analyst",
  "Associate",
  "Auditor",
  "Branch Manager",
  "Business Analyst",
  "Civil Engineer",
  "Claims Processor",
  "Clerk",
  "Collections Officer",
  "Consultant",
  "Coordinator",
  "Credit Analyst",
  "Customer Service Representative",
  "Data Analyst",
  "Data Encoder",
  "Database Administrator",
  "Electrical Engineer",
  "Engineer",
  "Executive Assistant",
  "Executive Secretary",
  "Finance Manager",
  "Financial Advisor",
  "Financial Analyst",
  "Graphic Designer",
  "HR Assistant",
  "HR Manager",
  "HR Officer",
  "HR Specialist",
  "HR Supervisor",
  "Information Technology Manager",
  "Internal Auditor",
  "IT Specialist",
  "IT Support",
  "Junior Accountant",
  "Junior Analyst",
  "Junior Developer",
  "Junior Engineer",
  "Legal Assistant",
  "Legal Counsel",
  "Logistics Coordinator",
  "Logistics Officer",
  "Management Trainee",
  "Manager",
  "Marketing Assistant",
  "Marketing Manager",
  "Marketing Officer",
  "Marketing Specialist",
  "Mechanical Engineer",
  "Network Administrator",
  "Office Clerk",
  "Office Manager",
  "Operations Manager",
  "Operations Supervisor",
  "Payroll Clerk",
  "Payroll Specialist",
  "Procurement Officer",
  "Production Manager",
  "Production Operator",
  "Production Supervisor",
  "Professor",
  "Programmer",
  "Project Engineer",
  "Project Manager",
  "Purchasing Assistant",
  "Purchasing Officer",
  "Quality Assurance Analyst",
  "Quality Assurance Inspector",
  "Receptionist",
  "Regulatory Affairs Officer",
  "Research Analyst",
  "Safety Officer",
  "Sales Associate",
  "Sales Executive",
  "Sales Manager",
  "Sales Representative",
  "Sales Supervisor",
  "Secretary",
  "Security Guard",
  "Senior Accountant",
  "Senior Analyst",
  "Senior Developer",
  "Senior Engineer",
  "Service Crew",
  "Software Developer",
  "Software Engineer",
  "Staff",
  "Store Manager",
  "Supervisor",
  "Supply Chain Manager",
  "Systems Administrator",
  "Systems Analyst",
  "Team Leader",
  "Technical Support",
  "Trainer",
  "Training Coordinator",
  "Training Manager",
  "Treasury Analyst",
  "Warehouse Supervisor",
  "Warehouse Worker",
  "Web Developer",
];
